/*  Script Atualização 18_05_22 
*** Ajuste Evitar erro de PrimaryKey ao inserir item durante a venda */ 
SET TERM ^ ;

create or alter procedure ST_CUPOM_ITEM_TEMP_INSERT (
    CODIGO varchar(50),
    COD_CUPOM varchar(50),
    ITEM integer,
    COD_PRODUTO integer,
    UNIDADE varchar(10),
    QTDE numeric(15,4),
    VALOR_UNITARIO numeric(15,3),
    VALOR_SUBTOTAL numeric(15,2),
    VALOR_DESCONTO numeric(15,2),
    VALOR_ACRESCIMO numeric(15,2),
    VALOR_TOTAL numeric(15,2),
    CST varchar(3),
    ALIQUOTA numeric(15,2),
    CANCELADO integer,
    COD_TOTALIZADOR varchar(7),
    TAMANHO char(5),
    COR char(5),
    POR_VOLUME integer,
    EXTRA blob sub_type 0 segment size 80,
    COMPLEMENTO varchar(50))
as
BEGIN
IF (NOT EXISTS (SELECT CODIGO FROM CUPOM_ITEM_TEMP CIT WHERE CIT.CODIGO =:CODIGO)) THEN
BEGIN
  INSERT INTO CUPOM_ITEM_TEMP
    (CODIGO, COD_CUPOM, ITEM, COD_PRODUTO, UNIDADE, QTDE,
     VALOR_UNITARIO, VALOR_SUBTOTAL, VALOR_DESCONTO, VALOR_ACRESCIMO,
     VALOR_TOTAL, CST, ALIQUOTA, CANCELADO, COD_TOTALIZADOR, TAMANHO, COR, POR_VOLUME, EXTRA,COMPLEMENTO)
  VALUES
    (:CODIGO, :COD_CUPOM, :ITEM, :COD_PRODUTO, :UNIDADE, :QTDE,
     :VALOR_UNITARIO, :VALOR_SUBTOTAL, :VALOR_DESCONTO, :VALOR_ACRESCIMO,
     :VALOR_TOTAL, :CST, :ALIQUOTA, :CANCELADO, :COD_TOTALIZADOR,
     :TAMANHO, :COR, :POR_VOLUME, :EXTRA,:COMPLEMENTO);
END
ELSE
BEGIN
  UPDATE CUPOM_ITEM_TEMP SET
    COD_CUPOM =:COD_CUPOM, ITEM = :ITEM, COD_PRODUTO =:ITEM, UNIDADE =:UNIDADE, QTDE =:QTDE,
    VALOR_UNITARIO =:VALOR_UNITARIO, VALOR_SUBTOTAL =:VALOR_SUBTOTAL, VALOR_DESCONTO =:VALOR_DESCONTO, VALOR_ACRESCIMO =:VALOR_ACRESCIMO,
    VALOR_TOTAL =:VALOR_TOTAL, CST =:CST, ALIQUOTA =:ALIQUOTA, CANCELADO =:CANCELADO, COD_TOTALIZADOR =:COD_TOTALIZADOR, TAMANHO =:TAMANHO,
    COR =:COR, POR_VOLUME =:POR_VOLUME, EXTRA =:EXTRA,COMPLEMENTO =:COMPLEMENTO
  WHERE CUPOM_ITEM_TEMP.CODIGO =:CODIGO;
END
SUSPEND;

END^

create or alter procedure ST_CUPOM_TEMP_DELETE (
    NUMERO_CUPOM varchar(50))
as
begin
  DELETE FROM CUPOM_TEMP
  WHERE CUPOM_TEMP.NUMERO = COALESCE(TRIM(:NUMERO_CUPOM),CUPOM_TEMP.NUMERO);

  DELETE FROM CUPOM_ITEM_TEMP
  WHERE CUPOM_ITEM_TEMP.COD_CUPOM = COALESCE(TRIM(:NUMERO_CUPOM),CUPOM_ITEM_TEMP.COD_CUPOM);
  suspend;
end^

SET TERM ; ^
